# fastq-dir is the input sample directory
#fastq-dir: /OSM/CBR/AF_DATASCHOOL/input/2019-04-12_Transcritome
fastq-dir: /scratch1/col52j/sm_test_data/

# Output directory
output-dir: /scratch1/col52j/sm_test/

# TODO: do I need this? Or just give Trinity 20 threads in the rule and use
# the snakemake -j argument to constrain?
# Trinity max threads
max-threads: 20
