cluster:                    "profiles/slurm/submit -J {cluster.job-name} -t {cluster.time} -p {cluster.partition} -A {cluster.account} -n {cluster.ntasts -c {cluster.cpus_per_task} -m {cluster.mem} -o {cluster.output} -d '{dependencies}'"
cluster-status:                 "status"
jobscript:                      "jobscript"
restart-times:                  2
max-jobs-per-second:            5
max-status-check-per-second:    5
local-cores:                    8
jobs:                           100  